### ISSUE TITLE
ncm source

### ISSUE THREAD

**Issue by roxma** [roxma/elm-vim#1]
Moving discussion https://github.com/roxma/nvim-completion-manager/issues/50#issuecomment-300990099 to this issue

@charliesbox 

> did you added an extra config along with the plugin?

> When I press, for example, String., I don't receive a completion of the functions

Make sure you have elm-oracle installed.  You could use elm-vim's omni-complete function `<c-x><c-o>` to test it. If there's a popup menu opened, then elm-vim is working.

If elm-vim's omni complete is working, and NCM is not, I'll need the log files generated by ncm, following the trouble-shooting instructions described at https://github.com/roxma/nvim-completion-manager#trouble-shooting

**Comment by charliesbox** [comment]
I do have installed elm-oracle.

When I press those commands, a popup opened, but it shows just the words that I already wrote, not the ones related to the methods of, for example, `String` module

Or that the expected behavior of the omni-complete function?

I'm looking for the logs :)

**Comment by roxma** [comment]
> Or that the expected behavior of the omni-complete function?

The existing omni-complete of elm-vim should be considered as the expected behavior.

 If the popup items of ncm are the same as the omni completion, then it should be considered as the expected behavior too.

**Comment by charliesbox** [comment]
Oh, I found something ! By using `let g:elm_detailed_complete = 1` it autocompletes with the functions inside a package

So String. will trigger all the options related to that package.

Although, with ncm, after a `.` nothing happens. Will go deeper on the logs. (But by using cx - co, the options are displayed)

**Comment by roxma** [comment]
> Oh, I found something ! By using let g:elm_detailed_complete = 1 it autocompletes with the functions inside a package

As far as I know this option only affects how the popup menu text is rendered. It does not stop or allow  items popping popup.

**Comment by charliesbox** [comment]
hi @roxma 

I was doing more testing today. I attached the logs that you ask me for.

When I press `cx - co`, the completion options are displayed. But, if I write a word, after I write the dot, for example `Html.`, the autocompletion is not displayed by default.

Please, let me know if you need more info. And thank you for your help!

[logs.zip](https://github.com/roxma/elm-vim/files/1009802/logs.zip)

**Comment by charliesbox** [comment]
after some restarts, it is working!

it looks ready to be part of the official elm repo. thanks @roxma !

**Comment by roxma** [comment]
https://github.com/ElmCast/elm-vim/pull/122
